# Generated by Django 6.0.2 on 2026-03-10 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('system_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LensPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_for_sunglasses', models.BooleanField(default=False)),
                ('is_for_eyeglasses', models.BooleanField(default=True)),
                ('type', models.ForeignKey(blank=True, limit_choices_to={'group__name': 'Lens Type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_core.metadataitem')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenses', to='vision.lenspackage')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_sphere', models.CharField(max_length=10)),
                ('od_cylinder', models.CharField(max_length=10)),
                ('od_axis', models.CharField(max_length=10)),
                ('os_sphere', models.CharField(max_length=10)),
                ('os_cylinder', models.CharField(max_length=10)),
                ('os_axis', models.CharField(max_length=10)),
                ('pd_distance', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_prescriptions', to='crm.employee')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'group__name': 'Prescription Status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_core.metadataitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
