# Generated by Django 6.0.3 on 2026-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text shown in the top announcement bar.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji or Lucide icon name.', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EditorialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cms/editorial/')),
                ('button_text', models.CharField(default='Explore More', max_length=50)),
                ('button_link', models.CharField(default='/products', max_length=255)),
                ('alignment', models.CharField(choices=[('left', 'Image Left, Text Right'), ('right', 'Text Left, Image Right')], default='left', max_length=10)),
                ('background_color', models.CharField(default='var(--bg-secondary, #f9fafb)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(help_text='Banner image for the hero section.', upload_to='cms/hero/')),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.CharField(default='/products', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('arrivals', 'New Arrivals'), ('style', 'Shop by Style'), ('collections', 'Featured Collections'), ('trending', 'Trending Now'), ('benefits', 'Why Choose Us')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
