# Generated by Django 6.0.3 on 2026-04-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Visit the Atelier', max_length=200)),
                ('description', models.TextField(help_text='Brief intro about the store location.')),
                ('address_title', models.CharField(default='Store Address', max_length=100)),
                ('address', models.TextField()),
                ('timings_title', models.CharField(default='Timings', max_length=100)),
                ('timings', models.CharField(default='Monday - Sunday: 10:00 AM - 9:00 PM', max_length=255)),
                ('map_image', models.ImageField(help_text='Static map image or placeholder.', upload_to='cms/contact/')),
                ('map_link', models.URLField(blank=True, help_text='Google Maps URL.')),
            ],
            options={
                'verbose_name_plural': 'Contact Settings',
            },
        ),
        migrations.CreateModel(
            name='NewsletterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Elevate Your Style', max_length=200)),
                ('description', models.TextField(default='Join our elite community and stay updated with the latest in premium eyewear.')),
                ('input_placeholder', models.CharField(default='Your email address', max_length=100)),
                ('button_text', models.CharField(default='Subscribe Now', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Newsletter Configuration',
            },
        ),
        migrations.CreateModel(
            name='PageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('shop', 'Shop All'), ('detail', 'Product Detail'), ('cart', 'Cart'), ('checkout', 'Checkout')], max_length=20, unique=True)),
                ('seo_title', models.CharField(help_text='Browser title tag.', max_length=200)),
                ('seo_description', models.TextField(help_text='Meta description.')),
            ],
            options={
                'verbose_name_plural': 'Page Metadata',
            },
        ),
    ]
