# Generated by Django 6.0.3 on 2026-04-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_contactsettings_newsletterconfig_pagemetadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSettings',
        ),
        migrations.DeleteModel(
            name='NewsletterConfig',
        ),
        migrations.DeleteModel(
            name='PageMetadata',
        ),
    ]
