# Generated by Django 6.0.3 on 2026-05-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_delete_contactsettings_delete_newsletterconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='SpecsIt', max_length=100)),
                ('meta_title_template', models.CharField(default='{product_name} | SpecsIt', help_text='Placeholders: {product_name}, {brand}, {category}, {store_name}', max_length=255)),
                ('meta_description_template', models.TextField(default='Buy {product_name} online at SpecsIt. Premium eyewear with fast delivery and best prices.', help_text='Placeholders: {product_name}, {brand}, {category}, {store_name}')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
