# Generated by Django 6.0.3 on 2026-05-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_update_site_settings_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description_template',
            field=models.TextField(default='Buy {product_name} in {variant_name} at {store_name}. Shop premium eyewear online.', help_text='Placeholders: {product_name}, {variant_name}, {brand}, {category}, {store_name}'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title_template',
            field=models.CharField(default='{product_name} | {variant_name} | {store_name}', help_text='Placeholders: {product_name}, {variant_name}, {brand}, {category}, {store_name}', max_length=255),
        ),
    ]
