# Generated by Django 6.0.3 on 2026-06-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_sitesettings_meta_description_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sizesettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
