# Generated by Django 6.0.3 on 2026-07-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='button_link',
            field=models.CharField(blank=True, default='/products', max_length=255),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_text',
            field=models.CharField(blank=True, default='Shop Now', max_length=50),
        ),
    ]
