# Generated by Django 6.0.3 on 2026-07-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_sitesettings_return_window_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='warranty_window_days',
            field=models.PositiveIntegerField(default=365),
        ),
    ]
