# Generated by Django 6.0.3 on 2026-07-21 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_delete_manufacturer_and_more'),
        ('cms', '0024_migrate_catalog_brand_to_brandlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandlogo',
            name='brand_type',
            field=models.CharField(choices=[('Frame', 'Frame'), ('Lens', 'Lenses for Frames'), ('Contact', 'Contact Lenses'), ('Cases', 'Cases'), ('Cloths', 'Cloths'), ('Solutions', 'Cleaning Solutions')], default='Frame', max_length=10),
        ),
        migrations.AddField(
            model_name='brandlogo',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='brand_logos', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='brandlogo',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandlogo',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
