# Generated by Django 6.0.3 on 2026-07-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_brandlogo_brand_type_brandlogo_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandlogo',
            name='in_corousel',
            field=models.BooleanField(default=True),
        ),
    ]
