# Generated by Django 6.0.3 on 2026-07-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0088_category_cat_parent_active_idx_and_more'),
        ('cms', '0026_brandlogo_in_corousel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brandlogo',
            index=models.Index(fields=['brand_type', 'is_published'], name='brand_type_published_idx'),
        ),
    ]
