# Generated by Django 6.0.3 on 2026-08-08 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_home_content_to_cms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='image_compression_enabled',
            field=models.BooleanField(default=True, help_text='Re-encode uploaded images. Turn off to store originals byte-for-byte.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='image_compression_quality',
            field=models.PositiveSmallIntegerField(default=82, help_text='Encoder quality, 40–100. 80–85 is visually lossless for photos.', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='image_max_dimension_px',
            field=models.PositiveIntegerField(default=2000, help_text='Longest edge, in pixels. Larger uploads are downscaled to fit.', validators=[django.core.validators.MinValueValidator(320), django.core.validators.MaxValueValidator(8000)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='image_output_format',
            field=models.CharField(choices=[('webp', 'WebP — smallest, keeps transparency'), ('jpeg', 'JPEG — widest compatibility, no transparency'), ('original', 'Keep original format')], default='webp', help_text='Format uploaded images are re-encoded to.', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_upload_size_mb',
            field=models.PositiveSmallIntegerField(default=5, help_text='Largest a stored asset may be. Images are compressed first, so the cap only rejects files that still exceed it afterwards.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
