# Generated by Django 6.0.2 on 2026-03-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_name_alter_manufacturer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='vto_image_front',
            field=models.ImageField(blank=True, null=True, upload_to='vto_assets/'),
        ),
    ]
