# Generated by Django 6.0.2 on 2026-03-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_variant_vto_image_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='vto_video',
            field=models.FileField(blank=True, null=True, upload_to='vto_assets/'),
        ),
    ]
