# Generated by Django 6.0.3 on 2026-03-25 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_variant_vto_video'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LensPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='bridge_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='frame_material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='frame_shape',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='hinge_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='lens_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lens_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='temple_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('index', models.CharField(blank=True, max_length=10)),
                ('is_for_sunglasses', models.BooleanField(default=False)),
                ('is_for_eyeglasses', models.BooleanField(default=True)),
                ('type', models.ForeignKey(blank=True, limit_choices_to={'group__name': 'Lens Type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.metadataitem')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenses', to='catalog.lenspackage')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_sphere', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('od_cylinder', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('od_axis', models.IntegerField(default=0)),
                ('od_add', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('os_sphere', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('os_cylinder', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('os_axis', models.IntegerField(default=0)),
                ('os_add', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pd_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pd_type', models.CharField(choices=[('binocular', 'Binocular'), ('monocular', 'Monocular')], default='binocular', max_length=20)),
                ('prism_od', models.CharField(blank=True, max_length=20)),
                ('prism_base_od', models.CharField(blank=True, max_length=20)),
                ('prism_os', models.CharField(blank=True, max_length=20)),
                ('prism_base_os', models.CharField(blank=True, max_length=20)),
                ('vision_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'group__name': 'Prescription Status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.metadataitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='face_captures/')),
                ('pd_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_capture_v2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
