# Generated by Django 6.0.3 on 2026-03-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_lenspackage_product_bridge_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/'),
        ),
    ]
