# Generated by Django 6.0.3 on 2026-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_collection_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='status',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
