# Generated by Django 6.0.3 on 2026-03-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_status_brand_is_active_collection_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Unisex', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='glass_type',
            field=models.CharField(choices=[('Eyeglasses', 'Eyeglasses'), ('Sunglasses', 'Sunglasses'), ('Reading Glasses', 'Reading Glasses')], default='Eyeglasses', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
