# Generated by Django 6.0.3 on 2026-03-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_brand_description_category_image_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lenspackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
