# Generated by Django 6.0.3 on 2026-03-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_lens_is_active_lens_name_lenspackage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
