# Generated by Django 6.0.3 on 2026-03-31 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_prescription_patient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='frame_material',
            new_name='frame_width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bridge_width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='glass_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hinge_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lens_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lens_width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='temple_length',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='frame_only_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='color_code',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='variant',
            name='color_selection_method',
            field=models.CharField(choices=[('code', 'Color Code'), ('palette', 'Palette Image')], default='code', max_length=10),
        ),
        migrations.AddField(
            model_name='variant',
            name='palette_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/palettes/'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Overrides base price if set', max_digits=10),
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.variant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
