# Generated by Django 6.0.3 on 2026-03-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_frame_material_product_frame_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='discount_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='variant',
            name='discount_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='frame_color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='frame_material',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='frame_size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='frame_weight',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_bogo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='lens_color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='frame_shape',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='frame_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='frame_width',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(default='', help_text='Common color name for SEO/Display', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
