# Generated by Django 6.0.3 on 2026-04-28 12:39

from django.conf import settings
from django.db import migrations, models


def deduplicate_reviews(apps, schema_editor):
    """
    Keep only the most recent review per (product, user) pair.
    Any older duplicates are deleted before the unique constraint is applied.
    """
    Review = apps.get_model('catalog', 'Review')
    seen = set()
    for review in Review.objects.order_by('product_id', 'user_id', '-created_at'):
        key = (review.product_id, review.user_id)
        if key in seen:
            review.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_prescription_prescription_file_prescription_review_notes'),
        ('sales', '0007_ordertracking_delivery_agent_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_order_user',
        ),
        migrations.RunPython(deduplicate_reviews, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_review_per_product_user'),
        ),
    ]
