# Generated by Django 6.0.3 on 2026-05-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_add_cost_price_and_variant_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use_meta_template',
            field=models.BooleanField(default=True),
        ),
    ]
