# Generated by Django 6.0.3 on 2026-05-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_variant_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_type',
            field=models.CharField(choices=[('Frame', 'Frame'), ('Lens', 'Lenses for Frames'), ('Contact', 'Contact Lenses')], default='Frame', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Lens', 'Lenses for Frames'), ('Frame', 'Frame'), ('Contact', 'Contact Lenses')], default='Frame', max_length=10),
        ),
    ]
