# Generated by Django 6.0.3 on 2026-05-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_brand_type_and_category_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenspackage',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='lens_packages', to='catalog.brand'),
        ),
    ]
