# Generated by Django 6.0.3 on 2026-05-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_lenspackage_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lenspackage',
            name='brands',
        ),
        migrations.AddField(
            model_name='lens',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lenses', to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='lenspackage',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='lens_packages', to='catalog.category'),
        ),
    ]
