# Generated by Django 6.0.3 on 2026-05-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_lens_brand_package_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
    ]
