# Generated by Django 6.0.3 on 2026-05-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_remove_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='last_restocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='last_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
