# Generated by Django 6.0.3 on 2026-05-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_remove_category_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_type',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='lenspackage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='is_listed',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Lens', 'Lens'), ('Frame', 'Frame')], default='Frame', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='submission_type',
            field=models.CharField(blank=True, choices=[('manual_entry', 'Manual Entry'), ('pdf_upload', 'PDF Upload'), ('deferred', 'Deferred (15 Days)')], default=None, help_text='How the prescription was submitted', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the prescription was submitted (useful for tracking deferred submissions)', null=True),
        ),
    ]
