# Generated by Django 6.0.3 on 2026-05-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_variant_last_restocked_variant_last_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('frame', 'Frames'), ('lens', 'Contact Lenses'), ('accessory', 'Accessories')], default='frame', max_length=20),
        ),
    ]
