# Generated by Django 6.0.3 on 2026-05-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_category_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenspackage',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lenspackage',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lenspackage',
            name='warranty_months',
            field=models.IntegerField(default=0),
        ),
    ]
