# Generated by Django 6.0.3 on 2026-05-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_lenspackage_cost_price_lenspackage_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='stock_by_size',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
