# Generated by Django 6.0.3 on 2026-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_variant_stock_by_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='is_rimless',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lens',
            name='index',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Lens', 'Lens'), ('Frame', 'Frame')], default='Frame', max_length=10),
        ),
    ]
