# Generated by Django 6.0.3 on 2026-05-23 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_lens_is_rimless_category_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('required_index', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lens',
            name='is_rimless',
        ),
        migrations.AddField(
            model_name='lens',
            name='constraint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lenses', to='catalog.lensconstraint'),
        ),
    ]
