# Generated by Django 6.0.3 on 2026-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_lensconstraint_remove_lens_is_rimless_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensconstraint',
            name='applicable_indices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
