# Generated by Django 6.0.3 on 2026-05-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_lensconstraint_applicable_indices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lensconstraint',
            name='applicable_indices',
        ),
        migrations.RemoveField(
            model_name='lensconstraint',
            name='required_index',
        ),
    ]
