# Generated by Django 6.0.3 on 2026-05-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_remove_lensconstraint_applicable_indices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lens',
            name='constraint',
        ),
        migrations.AddField(
            model_name='lens',
            name='constraints',
            field=models.ManyToManyField(blank=True, related_name='lenses', to='catalog.lensconstraint'),
        ),
    ]
