# Generated by Django 6.0.3 on 2026-05-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_change_constraint_to_many_to_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_warranty_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
