# Generated by Django 6.0.3 on 2026-06-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_alter_stock_by_size_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='frame_size',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='frame_weight',
        ),
        migrations.AddField(
            model_name='variant',
            name='bride_lentgh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variant',
            name='lens_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variant',
            name='small',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variant',
            name='temple_length',
            field=models.IntegerField(default=0),
        ),
    ]
