# Generated by Django 6.0.3 on 2026-06-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_lens_max_power_lens_min_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='small',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='max_power',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='min_power',
        ),
    ]
