# Generated by Django 6.0.3 on 2026-06-09 08:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_rename_small_variant_quantity_remove_lens_max_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='max_power',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='lens',
            name='min_power',
            field=models.DecimalField(decimal_places=2, default=Decimal('-6.00'), max_digits=5),
        ),
    ]
