# Generated by Django 6.0.3 on 2026-06-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_add_contact_lens_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lenses/'),
        ),
    ]
