# Generated by Django 6.0.3 on 2026-06-23 10:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_lens_cyl_power_range'),
        ('core', '0003_metadataitem_home_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_lenses/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('min_power', models.DecimalField(decimal_places=2, default=Decimal('-6.00'), max_digits=5)),
                ('max_power', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5)),
                ('power_type', models.CharField(blank=True, max_length=50, null=True)),
                ('base_curve', models.JSONField(blank=True, default=list)),
                ('replacement', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('water_content', models.CharField(blank=True, max_length=20, null=True)),
                ('dkt', models.CharField(blank=True, max_length=20, null=True)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('lenses_per_box', models.IntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_lenses', to='catalog.brand')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lenses', to='catalog.lenspackage')),
                ('type', models.ForeignKey(blank=True, limit_choices_to={'group__name': 'Contact Lens Type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.metadataitem')),
            ],
        ),
    ]
