# Generated by Django 6.0.3 on 2026-06-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_rescue_contact_orphans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='is_warranty_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
