# Generated by Django 6.0.3 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_alter_variant_is_warranty_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
