# Generated by Django 6.0.3 on 2026-07-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0059_seed_accessory_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='accessory_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='compatibility',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='features',
            field=models.CharField(blank=True, default='', help_text='Comma-separated feature tags.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('lens', 'Lens'), ('frame', 'Frame'), ('accessory', 'Accessory')], default='frame', max_length=10),
        ),
    ]
