# Generated by Django 6.0.3 on 2026-07-19 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_variant_is_return_eligible'),
        ('sales', '0042_order_replaces_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'product_type', '-created_at'], name='prod_act_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='product_brand_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='product_category_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_bestseller', 'is_active'], name='product_bestseller_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['final_price'], name='product_final_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='product_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved', '-created_at'], name='review_product_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order', 'user'], name='review_order_user_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_featured', 'is_approved'], name='review_featured_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product', 'is_listed', 'stock'], name='var_prod_listed_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['sku'], name='variant_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['is_listed', 'stock'], name='variant_listed_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product', '-id'], name='variant_product_id_idx'),
        ),
    ]
