# Generated by Django 6.0.3 on 2026-07-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0064_analytics_snapshot_and_cart_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(db_index=True, default='', help_text='Common color name for SEO/Display', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='frame_color',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='frame_material',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
