# Generated by Django 6.0.3 on 2026-07-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0065_index_searched_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='country_of_origin',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='lens_color_code',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='variant',
            name='lens_color_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='lens_material',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='polarized',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='variant',
            name='sg_palette_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/palettes/sg/'),
        ),
        migrations.AddField(
            model_name='variant',
            name='uv_protection',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
