# Generated by Django 6.0.3 on 2026-07-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0066_variant_barcode_variant_country_of_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
