# Generated by Django 6.0.3 on 2026-07-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0067_remove_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('lens', 'Lens'), ('frame', 'Frame'), ('accessory', 'Accessory')], default='frame', max_length=10),
        ),
    ]
