# Generated by Django 6.0.3 on 2026-07-21 06:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0068_product_product_type'),
        ('cms', '0023_sitesettings_warranty_window_days'),
        ('sales', '0044_populate_missing_shipments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlens',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_lenses', to='cms.brandlogo'),
        ),
        migrations.AlterField(
            model_name='lens',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lenses', to='cms.brandlogo'),
        ),
        # Make `product.brand` nullable during this migration to avoid applying
        # an invalid datetime default as an FK id. A later migration should
        # enforce non-nullability if required.
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands_names', to='cms.brandlogo'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        # Note: Do not delete the legacy `Brand` and `Manufacturer` models here.
        # Other app migrations (sales, etc.) still reference `catalog.Brand` in
        # their historical state. Deleting the models here causes migration
        # state resolution errors. Remove the models in a later migration
        # once all dependent migrations have been applied.
    ]
