# Generated by Django 6.0.3 on 2026-07-21 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0070_delete_brand_rows'),
        ('cms', '0024_migrate_catalog_brand_to_brandlogo'),
    ]

    operations = [
        # Avoid deleting `Manufacturer` here — the table may already be absent
        # in some environments and other apps' migration histories may still
        # reference it. Keep `brand` unmanaged but make `product.brand` nullable
        # to avoid assigning an invalid datetime default as a foreign-key id.
        migrations.AlterModelOptions(
            name='brand',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands_names', to='cms.brandlogo'),
        ),
    ]
