# Generated by Django 6.0.3 on 2026-07-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0071_delete_manufacturer_alter_brand_options_and_more'),
    ]

    operations = [
        # Drop the legacy manufacturer table if it exists; some environments
        # may have already removed it. Use IF EXISTS to avoid errors.
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS catalog_manufacturer CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelTable(
            name='brand',
            table='catalog_brand',
        ),
    ]
