# Generated by Django 6.0.3 on 2026-07-21 08:07

from django.db import migrations




class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0072_delete_manufacturer_alter_brand_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS catalog_manufacturer CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
