# Generated by Django 6.0.3 on 2026-07-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0073_delete_manufacturer'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS catalog_manufacturer CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='Manufacturer',
                ),
            ],
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='bride_lentgh',
            new_name='bridge_length',
        ),
    ]
