# Generated by Django 6.0.3 on 2026-07-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_delete_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
