# Generated by Django 6.0.3 on 2026-07-21 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0075_remove_category_description_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
