# Generated by Django 6.0.3 on 2026-07-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0076_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
    ]
