# Generated by Django 6.0.3 on 2026-07-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0077_remove_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lens',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenses', to='catalog.lenspackage'),
        ),
        migrations.AlterField(
            model_name='contactlens',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lenses', to='catalog.lenspackage'),
        ),
    ]
