# Generated by Django 6.0.3 on 2026-07-22 04:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0078_alter_lens_package_delete_behavior'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 22, 4, 29, 32, 596263, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('frame', 'Frames'), ('lens', 'Lenses'), ('accessory', 'Accessories')], default='frame', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 7, 22, 4, 29, 43, 510661, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
