# Generated by Django 6.0.3 on 2026-07-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0079_delete_brand_alter_category_options_category_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='frame_width',
        ),
        migrations.AddField(
            model_name='variant',
            name='hing_width',
            field=models.IntegerField(default=0),
        ),
    ]
