# Generated by Django 6.0.3 on 2026-07-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0080_remove_product_frame_width_variant_hing_width'),
        ('cms', '0026_brandlogo_in_corousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_product_type', models.CharField(choices=[('cloths', 'cloths'), ('cases', 'cases'), ('cleaning_solutions', 'cleaning_solutions')], default='None', max_length=20)),
                ('accessory_name', models.CharField(blank=True, default='', max_length=20)),
                ('accessory_tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('accessory_material', models.CharField(blank=True, default='', max_length=20)),
                ('accessory_notes', models.TextField(blank=True)),
                ('features', models.CharField(blank=True, default='', help_text='Comma-separated feature tags.', max_length=255)),
                ('warranty_period', models.CharField(blank=True, default='', help_text='Warranty duration for cases, e.g. "1 Year".', max_length=50)),
                ('AccessoryCaseType', models.CharField(blank=True, default='', max_length=20)),
                ('AccessorySolution_ml', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('Accessory_case_dimensions', models.CharField(blank=True, default='', max_length=20)),
                ('Accessory_cloth_dimensions', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoriesVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccessoryesVariantName', models.CharField(blank=True, default='', max_length=20)),
                ('AccessoryesSKU', models.CharField(blank=True, default='', max_length=20)),
                ('AccessoryesColorName', models.CharField(blank=True, default='', max_length=20)),
                ('AccessoryColorCode', models.CharField(blank=True, default=' ', max_length=20)),
                ('AccessoryPalette', models.ImageField(blank=True, null=True, upload_to='')),
                ('stock', models.IntegerField(default=0)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('is_listed', models.BooleanField(default=True)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('last_sold', models.DateTimeField(blank=True, null=True)),
                ('vto_image_front', models.ImageField(blank=True, null=True, upload_to='vto_assets/')),
                ('vto_video', models.FileField(blank=True, null=True, upload_to='vto_assets/')),
                ('is_return_eligible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('product_type', models.CharField(choices=[('lens', 'Lens'), ('frame', 'Frame'), ('accessory', 'Accessory')], default='frame', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.CharField(blank=True, default='', max_length=255)),
                ('frame_material', models.CharField(blank=True, default='', max_length=100)),
                ('lens_material', models.CharField(blank=True, default='', max_length=100)),
                ('frame_shape', models.CharField(blank=True, default='', max_length=100)),
                ('frame_type', models.CharField(blank=True, default='', max_length=100)),
                ('frame_width', models.CharField(blank=True, default='', max_length=100)),
                ('frame_style', models.CharField(blank=True, default='', max_length=100)),
                ('frame_country_of_origin', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex'), ('Kids', 'Kids')], default='Unisex', max_length=20)),
                ('frame_tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('frame_only_mode', models.BooleanField(default=False)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(blank=True, default='', max_length=100)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('frame_color', models.CharField(blank=True, default='', max_length=100)),
                ('lens_color', models.CharField(blank=True, default='', max_length=10)),
                ('color_selection_method', models.CharField(choices=[('code', 'Color Code'), ('palette', 'Palette Image')], default='code', max_length=10)),
                ('color_code', models.CharField(blank=True, default='#000000', max_length=10)),
                ('palette_image', models.ImageField(blank=True, null=True, upload_to='catalog/palettes/')),
                ('lens_color_name', models.CharField(blank=True, default='', max_length=100)),
                ('lens_color_code', models.CharField(blank=True, default='#000000', max_length=10)),
                ('lens_palette_image', models.ImageField(blank=True, null=True, upload_to='catalog/palettes/sg/')),
                ('frame_material', models.CharField(blank=True, default='', max_length=100)),
                ('lens_material', models.CharField(blank=True, default='', max_length=100)),
                ('frame_shape', models.CharField(blank=True, default='', max_length=100)),
                ('frame_type', models.CharField(blank=True, default='', max_length=100)),
                ('frame_size', models.CharField(blank=True, default='', max_length=50)),
                ('weight', models.CharField(blank=True, default='', max_length=50)),
                ('frame_weight', models.CharField(blank=True, default='', max_length=50)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex'), ('Kids', 'Kids')], default='Unisex', max_length=20)),
                ('uv_protection', models.CharField(blank=True, default='', max_length=100)),
                ('polarized', models.CharField(blank=True, default='', max_length=50)),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=100)),
                ('frame_only_mode', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('stock_by_size', models.JSONField(blank=True, default=dict)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_bogo', models.BooleanField(default=False)),
                ('discount_start_date', models.DateField(blank=True, null=True)),
                ('discount_end_date', models.DateField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('use_meta_template', models.BooleanField(default=True)),
                ('vto_image_front', models.ImageField(blank=True, null=True, upload_to='vto_assets/')),
                ('vto_video', models.FileField(blank=True, null=True, upload_to='vto_assets/')),
                ('is_listed', models.BooleanField(default=True)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('last_sold', models.DateTimeField(blank=True, null=True)),
                ('is_warranty_eligible', models.BooleanField(default=False)),
                ('is_return_eligible', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_brand_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_category_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_bestseller_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_final_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_sku_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='var_prod_listed_stock_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='variant_sku_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='variant_listed_stock_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='variant_product_id_idx',
        ),
        migrations.AddField(
            model_name='accessoriesproduct',
            name='accessory_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessory_brands', to='cms.brandlogo'),
        ),
        migrations.AddField(
            model_name='accessoriesvariants',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.accessoriesproduct'),
        ),
        migrations.AddField(
            model_name='frameproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands_names', to='cms.brandlogo'),
        ),
        migrations.AddField(
            model_name='frameproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(related_name='collections', to='catalog.frameproduct'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.frameproduct'),
        ),
        migrations.AddField(
            model_name='framevariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.frameproduct'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.framevariant'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='product',
        ),
        migrations.AddIndex(
            model_name='accessoriesvariants',
            index=models.Index(fields=['is_listed'], name='acc_variant_listed_idx'),
        ),
        migrations.AddIndex(
            model_name='frameproduct',
            index=models.Index(fields=['is_active', 'product_type', '-created_at'], name='fprod_act_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='frameproduct',
            index=models.Index(fields=['brand', 'is_active'], name='fprod_brand_active_idx'),
        ),
        migrations.AddIndex(
            model_name='frameproduct',
            index=models.Index(fields=['category', 'is_active'], name='fprod_category_active_idx'),
        ),
        migrations.AddIndex(
            model_name='frameproduct',
            index=models.Index(fields=['is_bestseller', 'is_active'], name='fprod_bestseller_active_idx'),
        ),
        migrations.AddIndex(
            model_name='framevariant',
            index=models.Index(fields=['product', 'is_listed', 'stock'], name='fvar_prod_listed_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='framevariant',
            index=models.Index(fields=['sku'], name='fvar_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='framevariant',
            index=models.Index(fields=['is_listed', 'stock'], name='fvar_listed_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='framevariant',
            index=models.Index(fields=['product', '-id'], name='fvar_product_id_idx'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
