# Generated by Django 6.0.3 on 2026-07-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0081_accessoriesproduct_accessoriesvariants_frameproduct_and_more'),
        ('sales', '0046_alter_cart_variant_alter_orderitem_variant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
