# Generated by Django 6.0.3 on 2026-07-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0082_delete_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameproduct',
            name='frame_width',
        ),
    ]
