# Generated by Django 6.0.3 on 2026-07-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0083_remove_frameproduct_frame_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameproduct',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='framevariant',
            name='is_return_eligible',
        ),
        migrations.RemoveField(
            model_name='framevariant',
            name='is_warranty_eligible',
        ),
        migrations.AddField(
            model_name='frameproduct',
            name='is_return_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frameproduct',
            name='is_warranty_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
