# Generated by Django 6.0.3 on 2026-07-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0084_remove_frameproduct_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameproduct',
            name='product_image',
        ),
    ]
