# Generated by Django 6.0.3 on 2026-07-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0085_remove_frameproduct_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameproduct',
            name='frame_style',
        ),
    ]
