# Generated by Django 6.0.3 on 2026-07-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0086_remove_frameproduct_frame_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framevariant',
            name='polarized',
            field=models.BooleanField(default=False),
        ),
    ]
