# Generated by Django 6.0.3 on 2026-07-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0087_alter_framevariant_polarized'),
        ('cms', '0026_brandlogo_in_corousel'),
        ('core', '0007_metadataitem_parent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='cat_parent_active_idx'),
        ),
        migrations.AddIndex(
            model_name='lens',
            index=models.Index(fields=['type', 'is_active'], name='lens_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='lens',
            index=models.Index(fields=['is_for_sunglasses', 'is_active'], name='lens_sunglass_active_idx'),
        ),
        migrations.AddIndex(
            model_name='lens',
            index=models.Index(fields=['is_for_eyeglasses', 'is_active'], name='lens_eyeglass_active_idx'),
        ),
    ]
