# Generated by Django 6.0.3 on 2026-07-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0088_category_cat_parent_active_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoriesvariants',
            name='vto_image_front',
        ),
        migrations.RemoveField(
            model_name='accessoriesvariants',
            name='vto_video',
        ),
        migrations.RemoveField(
            model_name='framevariant',
            name='vto_image_front',
        ),
        migrations.RemoveField(
            model_name='framevariant',
            name='vto_video',
        ),
    ]
