# Generated by Django 6.0.3 on 2026-07-28 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0089_remove_accessoriesvariants_vto_image_front_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framevariant',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='framevariant',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='framevariant',
            name='use_meta_template',
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('use_meta_template', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='catalog.frameproduct')),
            ],
        ),
    ]
