# Generated by Django 6.0.3 on 2026-07-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0090_remove_framevariant_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlens',
            name='replacement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='replacement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
