# Generated by Django 6.0.3 on 2026-08-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0091_alter_contactlens_replacement_alter_lens_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userface',
            name='pd_confidence',
            field=models.CharField(blank=True, help_text='high / medium / low, as reported by the measurement.', max_length=10),
        ),
        migrations.AddField(
            model_name='userface',
            name='pd_left_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Left eye (OS) to nose bridge centre, mm.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userface',
            name='pd_method',
            field=models.CharField(blank=True, choices=[('card', 'Card reference (ID-1)'), ('manual', 'Entered manually'), ('face_ratio', 'Face-width ratio (legacy)')], help_text='How pd_distance was obtained.', max_length=20),
        ),
        migrations.AddField(
            model_name='userface',
            name='pd_right_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Right eye (OD) to nose bridge centre, mm.', max_digits=5, null=True),
        ),
    ]
