# Generated by Django 6.0.3 on 2026-08-17 16:23

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0092_userface_pd_confidence_userface_pd_left_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.catalog.models.prescription_upload_path),
        ),
        migrations.AlterField(
            model_name='userface',
            name='image',
            field=models.ImageField(upload_to=apps.catalog.models.face_capture_upload_path),
        ),
    ]
