# Generated by Django 6.0.3 on 2026-09-17 09:17

import apps.catalog.models
import apps.core_utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0094_product_variant_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, storage=apps.core_utils.storage.private_media_storage, upload_to=apps.catalog.models.prescription_upload_path),
        ),
        migrations.AlterField(
            model_name='userface',
            name='image',
            field=models.ImageField(storage=apps.core_utils.storage.private_media_storage, upload_to=apps.catalog.models.face_capture_upload_path),
        ),
    ]
