# Generated by Django 6.0.3 on 2026-03-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
