# Generated by Django 6.0.3 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_phone_to_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
