# Generated by Django 6.0.3 on 2026-07-27 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_bank_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='addr_user_default_idx'),
        ),
    ]
