# Generated by Django 6.0.3 on 2026-06-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lens_types/'),
        ),
    ]
