# Generated by Django 6.0.3 on 2026-06-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_lens_cyl_power_range'),
        ('core', '0002_metadataitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataitem',
            name='home_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category'),
        ),
    ]
