# Generated by Django 6.0.3 on 2026-06-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_metadataitem_home_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataitem',
            name='direct_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
