# Generated by Django 6.0.3 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_metadataitem_direct_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataitem',
            name='enable_pd',
            field=models.BooleanField(default=True),
        ),
    ]
