# Generated by Django 6.0.3 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_metadataitem_enable_pd'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataitem',
            name='skip_power',
            field=models.BooleanField(default=False),
        ),
    ]
