# Generated by Django 6.0.3 on 2026-06-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_metadataitem_skip_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.metadataitem'),
        ),
    ]
