# Generated by Django 6.0.3 on 2026-07-27 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0088_category_cat_parent_active_idx_and_more'),
        ('core', '0007_metadataitem_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analyticslog',
            index=models.Index(fields=['-timestamp'], name='analytics_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='metadataitem',
            index=models.Index(fields=['group', 'is_active'], name='meta_group_active_idx'),
        ),
    ]
