# Generated by Django 6.0.3 on 2026-06-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencyrecord',
            new_name='core_utils__idempot_0461bb_idx',
            old_name='core_utils_idempo_idempon_idx',
        ),
        migrations.RenameIndex(
            model_name='idempotencyrecord',
            new_name='core_utils__user_id_69c62f_idx',
            old_name='core_utils_idempo_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='idempotencyrecord',
            new_name='core_utils__created_ebf0e1_idx',
            old_name='core_utils_idempo_created_idx',
        ),
        migrations.RenameIndex(
            model_name='idempotencyrecord',
            new_name='core_utils__expires_de10dc_idx',
            old_name='core_utils_idempo_expires_idx',
        ),
    ]
