# Generated by Django 6.0.3 on 2026-08-17 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('core_utils', '0002_rename_core_utils_idempo_idempon_idx_core_utils__idempot_0461bb_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenActivity',
            fields=[
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='activity', serialize=False, to='authtoken.token')),
                ('last_used', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Token Activity',
            },
        ),
    ]
