# Generated by Django 6.0.3 on 2026-03-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
