# Generated by Django 6.0.3 on 2026-03-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('current_page', models.CharField(default='Home Page', max_length=255)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
