# Generated by Django 6.0.3 on 2026-04-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_livesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe (Future)')], default='razorpay', max_length=50, unique=True)),
                ('key_id', models.CharField(blank=True, help_text='Razorpay Key ID', max_length=255)),
                ('key_secret', models.CharField(blank=True, help_text='Razorpay Key Secret', max_length=255)),
                ('is_sandbox', models.BooleanField(default=True, help_text='Toggle between Test and Live mode')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Gateway Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to be collected on delivery', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount already paid online', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Full Online Payment'), ('PARTIAL', 'Partial (Online + COD)')], default='COD', max_length=50),
        ),
    ]
