# Generated by Django 6.0.3 on 2026-04-29 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_fix_review_unique_constraint_per_product'),
        ('sales', '0007_ordertracking_delivery_agent_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.prescription'),
        ),
    ]
