# Generated by Django 6.0.3 on 2026-05-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_add_prescription_related_name_to_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='qc_image',
            field=models.ImageField(blank=True, null=True, upload_to='qc/'),
        ),
    ]
