# Generated by Django 6.0.3 on 2026-05-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_returnrequest_warrantyclaim'),
    ]

    operations = [
    ]
