# Generated by Django 6.0.3 on 2026-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_merge_20260510_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready_to_dispatch', 'Ready to Dispatch'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
