# Generated by Django 6.0.3 on 2026-05-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_add_preparing_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready_to_dispatch', 'Ready to Dispatch'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
