# Generated by Django 6.0.3 on 2026-05-20 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_orderitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('courier_company', models.CharField(blank=True, max_length=100, null=True)),
                ('current_status', models.CharField(default='pending', max_length=50)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_agent_name', models.CharField(blank=True, max_length=100)),
                ('delivery_agent_phone', models.CharField(blank=True, max_length=20)),
                ('qc_image', models.ImageField(blank=True, null=True, upload_to='qc/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='sales.orderitem')),
            ],
        ),
    ]
