# Generated by Django 6.0.3 on 2026-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='service_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
