# Generated by Django 6.0.3 on 2026-05-20 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_variant_last_restocked_variant_last_sold'),
        ('sales', '0017_orderitemtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this coupon is applicable for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='catalog.category'),
        ),
    ]
