# Generated by Django 6.0.3 on 2026-05-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_ordertracking_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='prescription_deferred_until',
            field=models.DateTimeField(blank=True, help_text='If deferred, this is when the 15-day window expires', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='prescription_submission_type',
            field=models.CharField(blank=True, choices=[('manual_entry', 'Manual Entry'), ('pdf_upload', 'PDF Upload'), ('deferred', 'Deferred (15 Days)')], default=None, help_text='Tracks how the prescription was submitted for this specific item', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='prescription_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the prescription was actually submitted (useful for tracking deferred submissions)', null=True),
        ),
    ]
