# Generated by Django 6.0.3 on 2026-05-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_variant_last_restocked_variant_last_sold'),
        ('sales', '0018_coupon_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='category',
        ),
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this coupon applies to. Leave empty to apply to all categories.', related_name='coupons', to='catalog.category'),
        ),
    ]
