# Generated by Django 6.0.3 on 2026-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_remove_coupon_category_coupon_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order_received', 'Order Received'), ('order_accepted', 'Order Accepted'), ('preparing_glasses', 'Preparing Glasses'), ('quality_check', 'Quality Check'), ('ready_to_dispatch', 'Ready to Dispatch'), ('in_transit', 'In Transit / Out for Delivery'), ('delivered', 'Delivered')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('order_received', 'Order Received'), ('order_accepted', 'Order Accepted'), ('preparing_glasses', 'Preparing Glasses'), ('quality_check', 'Quality Check'), ('ready_to_dispatch', 'Ready to Dispatch'), ('in_transit', 'In Transit / Out for Delivery'), ('delivered', 'Delivered')], default='pending', max_length=30),
        ),
    ]
