# Generated by Django 6.0.3 on 2026-06-15 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_ordertracking_delivery_rate_charged'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('page', models.CharField(max_length=500)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='desktop', max_length=10)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id', 'visited_at'], name='sales_sitev_session_716f5e_idx'), models.Index(fields=['visited_at', 'device_type'], name='sales_sitev_visited_1d8cab_idx')],
            },
        ),
    ]
