# Generated by Django 6.0.3 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_returnrequestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='tracking_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
