# Generated by Django 6.0.3 on 2026-06-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_returnrequestnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyclaim',
            name='preferred_fix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='WarrantyClaimImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='warranty_claims/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warranty_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sales.warrantyclaim')),
            ],
        ),
    ]
