# Generated by Django 6.0.3 on 2026-07-14 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_returnrequest_refund_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='picked_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_agent_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_agent_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_slot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_tracking_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='received_condition',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='received_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='replacement_courier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ReturnReceivedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='return_received/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_images', to='sales.returnrequest')),
            ],
        ),
    ]
