# Generated by Django 6.0.3 on 2026-07-14 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_returnrequest_picked_up_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPickupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='return_pickup/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_images', to='sales.returnrequest')),
            ],
        ),
    ]
