# Generated by Django 6.0.3 on 2026-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_returnpickupimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='replacement_price_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
