# Generated by Django 6.0.3 on 2026-07-14 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_variant_is_return_eligible'),
        ('sales', '0037_returnrequest_replacement_price_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='replacement_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_returns', to='sales.order'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='replacement_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.variant'),
        ),
    ]
