# Generated by Django 6.0.3 on 2026-07-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_returnrequest_replacement_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='replacement_payment_ref',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
