# Generated by Django 6.0.3 on 2026-07-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_returnrequest_replacement_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to='sales.orderitem'),
        ),
    ]
