# Generated by Django 6.0.3 on 2026-07-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_returnrequest_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_replacement',
            field=models.BooleanField(default=False),
        ),
    ]
