# Generated by Django 6.0.3 on 2026-07-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_order_is_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='replaces_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_orders', to='sales.order'),
        ),
    ]
