# Generated by Django 6.0.3 on 2026-07-19 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_bank_account'),
        ('catalog', '0064_analytics_snapshot_and_cart_index'),
        ('core', '0007_metadataitem_parent'),
        ('sales', '0042_order_replaces_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('last_7', 'Last 7 Days'), ('last_30', 'Last 30 Days'), ('last_90', 'Last 90 Days'), ('this_week', 'This Week')], db_index=True, max_length=20, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('is_stale', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='cart_user_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['variant'], name='cart_variant_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['-added_at'], name='cart_added_at_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='order_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status', '-created_at'], name='order_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'payment_status'], name='order_method_pstatus_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='order_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_date'], name='order_delivery_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_replacement', '-created_at'], name='order_replacement_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='order_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-updated_at'], name='order_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orderitem_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['variant'], name='orderitem_variant_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['contact_lens'], name='orderitem_contact_lens_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['status'], name='orderitem_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'payment_status'], name='payment_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', 'status'], name='returnreq_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['request_type', 'status'], name='returnreq_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['-created_at'], name='returnreq_created_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyclaim',
            index=models.Index(fields=['order', 'status'], name='warrantyclaim_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyclaim',
            index=models.Index(fields=['status'], name='warrantyclaim_status_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user'], name='wishlist_user_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['period'], name='analytics_snapshot_period_idx'),
        ),
    ]
