# Generated by Django 6.0.3 on 2026-07-19 19:56

from django.db import migrations


def create_missing_shipments(apps, schema_editor):
    Order = apps.get_model('sales', 'Order')
    Shipment = apps.get_model('sales', 'Shipment')
    MetadataGroup = apps.get_model('core', 'MetadataGroup')
    MetadataItem = apps.get_model('core', 'MetadataItem')

    shipment_grp, _ = MetadataGroup.objects.get_or_create(name='Shipment Status')
    shipment_status, _ = MetadataItem.objects.get_or_create(
        group=shipment_grp, 
        label='Processing', 
        defaults={'value': 'processing', 'is_active': True}
    )

    orders_without_shipments = Order.objects.filter(shipment__isnull=True)
    shipments_to_create = []
    
    for order in orders_without_shipments:
        shipments_to_create.append(
            Shipment(
                order=order,
                carrier='Pending',
                method='Standard',
                status=shipment_status
            )
        )
        
    if shipments_to_create:
        Shipment.objects.bulk_create(shipments_to_create)

def reverse_missing_shipments(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_analytics_snapshot_and_cart_index'),
    ]

    operations = [
        migrations.RunPython(create_missing_shipments, reverse_missing_shipments),
    ]
