# Generated by Django 6.0.3 on 2026-07-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_sitesettings_warranty_window_days'),
        ('sales', '0044_populate_missing_shipments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='brands',
            field=models.ManyToManyField(blank=True, help_text='Brands this coupon applies to. Leave empty to apply to all brands.', related_name='coupons', to='cms.brandlogo'),
        ),
    ]
