# Generated by Django 6.0.3 on 2026-07-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0081_accessoriesproduct_accessoriesvariants_frameproduct_and_more'),
        ('sales', '0045_alter_coupon_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.framevariant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.framevariant'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='replacement_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.framevariant'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.framevariant'),
        ),
    ]
