# Generated by Django 6.0.3 on 2026-08-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_alter_cart_variant_alter_orderitem_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='qc_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='qc_issue_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='qc_status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
